# Generated by Django 4.1.3 on 2022-12-07 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasktest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskTest',
        ),
    ]
